import os

MQTT_HOST = "mqtt.cloud.yandex.net"
MQTT_PORT = 8883
MQTT_KEEPALIVE = 2
MQTT_WAIT_FOR_STATE_TIMEOUT = 5
MQTT_WAIT_FOR_STATE_CHANGE_TIMEOUT = 5
MQTT_WAIT_FOR_CONNECTION_EVENT = 10

CERTIFICATE_PATH = "rootCA.crt"

REGISTRY_ID = os.environ['REGISTRY_ID']
REGISTRY_PASSWORD = os.environ['REGISTRY_PASSWORD']

PUSHER_ID = "pusher"
PUSHER_DEVICE_ID = os.environ['PUSHER_DEVICE_ID']
PUSHER_PASSWORD = os.environ['PUSHER_DEVICE_PASSWORD']

TEST_PUSHER_ID = "pushernodemcu"
TEST_PUSHER_DEVICE_ID = os.environ['TEST_PUSHER_DEVICE_ID']
TEST_PUSHER_PASSWORD = os.environ['TEST_PUSHER_DEVICE_PASSWORD']